baseURL = "http://msbeigi.com/"
# [en, zh-cn, fr, ...] determines default content language
defaultContentLanguage = "en"
# language code
languageCode = "en"
title = "Mohsen Sadeghbeigi"

# Change the default theme to be use when building the site with Hugo
theme = "FeelIt"

[params]
  # FeelIt theme version
  version = "1.0.X"
  [params.footer]
    enable = true
    custom = '<p>Mohsen Sadeghbeigi</p>'
    copyright = true
    author = true
    since = 2021
    hugo = false

  [params.section]
    paginate = 20
    dateFormat = "01-02"
    rss = 10

  [params.about]
    enable = true

  [params.home]
    rss = 10
    
    [params.home.profile]
      enable = true
      gravatarEmail = "msbeigi83@gmail.com"
      avatarURL = "/images/avatar.png"
      title = "Mohsen Sadeghbeigi"
      subtitle = "This is my blog, you can find something to worth reading in here"
      typeit = true
      social = true

    [params.home.posts]
      enable = true
      paginate = 6
      imagePreview = true
      defaultHiddenFromHomePage = false

    [params.social]
      GitHub = "msbeigiai"
      Linkedin = "mohsen-sadeghbeigi-628a68204"
      Twitter = "msbeigiai"
      Youtubechannel = "/UC-YX0aht99KRRS3KozulLFg"
      Email = "msbeigi83@gmail.com"
      rss = true
